### ISSUE TITLE
Remove empty string check in messages.yml for format.message

### ISSUE THREAD

**Issue by mdsimmo** [mdsimmo/bomberman#34]
### What happened?

From `default_messages.yml`:
```yaml
format:
  # How a basic message looks
  # TODO remove need for empty message check
  # {message}: the message being sent
  message: '{#switch|{message}|||{#green|[Bomberman]} {message}}'
```

### Bomberman Version

v0.8.3

### Minecraft Version

-

### Java Version

-
